/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "StdTypes.h"
#include "Utils.h"

#include "RCC_Interface.h"
#include "GPIO_interface.h"
#include "LCD_interface.h"
#include "NVIC_interface.h"
#include "EXTI_interface.h"
#include "STK_interface.h"
#include "ADC_interface.h"
#include "Timer_private.h"
#include "Timer_interface.h"
#include "UART_interface.h"



#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/********************************************************/

/*		Static Screens  */
#define   	 SCREEN1L0					"  Welcome To    "
#define   	 SCREEN1L1					"  Smart Home.   "

#define   	 SCREEN2L0					"System Main D:  "
#define   	 SCREEN2L1					"L:    % S:    % "

#define   	 SCREEN3L0					"    INVALID     "
#define   	 SCREEN3L1					"  !!COMMAND!!   "

#define   	 SCREEN4L0					"     DOOR       "
#define   	 SCREEN4L1					"    OPENED      "
#define   	 SCREEN4L1_2				"    CLOSED      "

#define   	 SCREEN5L0					"     FAN        "
#define   	 SCREEN5L0_2			    "    LIGHTS      "
#define   	 SCREEN5L1					"    MANUAL      "
#define   	 SCREEN5L1_2				"     AUTO       "


#define    Welcome_Screen_Delay      3000000
#define    Events_Screen_Delay       1000000
#define    LDR_UPDATE_COUNT          100000
#define    POT_UPDATE_COUNT          100000


typedef enum {
	RECIVING_COMMANDS,           /* TIME BASED  */
	COMMAND1_VALID	,            /* EVENT BASED */
	COMMAND2_VALID	,            /* EVENT BASED */
	COMMAND3_VALID	,            /* EVENT BASED */
	COMMAND4_VALID	,            /* EVENT BASED */
	COMMAND5_VALID	,            /* EVENT BASED */
	COMMAND6_VALID	,            /* EVENT BASED */
	COMMAND7_VALID	,            /* EVENT BASED */
	COMMAND8_VALID	,            /* EVENT BASED */
	COMMAND9_VALID	,            /* EVENT BASED */
	COMMAND10_VALID	,            /* EVENT BASED */
	COMMAND11_VALID	,            /* EVENT BASED */
	COMMAND12_VALID	,            /* EVENT BASED */
	COMMAND13_VALID	,            /* EVENT BASED */
	COMMAND14_VALID	,            /* EVENT BASED */
	COMMAND15_VALID	,            /* EVENT BASED */
	COMMANDS_UNVALID,            /* EVENT BASED */
	CHECKING_COMMANDS_VIDALITY,  /* EVENT BASED */
	RECIVING_ADC_READINGS        /* TIME BASED  */
	//CALLING_USER_BACK,		 /* EVENT BASED */

}System_States;
/********************************************************/

#define OPEN_CLOSE_LOCK      'D'
#define FAN_AUTO_MANUAL      'F'
#define LIGHT_AUTO_MANUAL    'L'

#define STOP_LIGHT           '1'
#define START_LIGHT_10       '2'
#define START_LIGHT_25       '3'
#define START_LIGHT_50       '4'
#define START_LIGHT_75       '5'
#define START_LIGHT_100      '6'

#define STOP_FAN             '7'
#define START_FAN_10         '8'
#define START_FAN_25         '9'
#define START_FAN_50         'A'
#define START_FAN_75         'B'
#define START_FAN_100        'C'

/***************************END****************************/

#define LIGHT_AUTO    'A'
#define LIGHT_MANUAL  'M'
#define FAN_AUTO      'A'
#define FAN_MANUAL    'M'
#define LOCK_OPEN     'O'
#define LOCK_CLOSE    'C'


int main(void)
{
	/********************* Global declerations ******************/

	System_States  CurrentState = RECIVING_COMMANDS ;
	//static u8 Command[200]={0};
	/*	Timer declecartion && PWM Decleration  				*/
	Timer_Config_type timer3={_TIM3,  PRELOAD, UPCOUNTER , DISABLE, 8 } ;      /* prescaller 8MHz/80 =100KHz and TickTime 10us */
	PWM_Config_type  PWM3_CH3={_TIM3,TIM_CHANNEL3,EDGE_ALIGN,MODE1_START_HIGH,1,50,0};    /*2% Angel 0--10% Angel 180*/
	PWM_Config_type  PWM3_CH4={_TIM3,TIM_CHANNEL4,EDGE_ALIGN,MODE1_START_HIGH,1,50,0};
	/*  UART  declecartion                   				*/
	UART_init_type uart1 ={ ID_UART1 ,  STRTBIT_8DATA_NSTOPBIT , NO_PARITY,  STOP_1_BIT ,DMA_TX_DISABLE, DMA_RX_DISABLE ,RATE_9600};
	/* 	RCC External Crystal	FCPU=8MHz		*/
	RCC_voidInit();
	RCC_voidEnablePeripheralClock_EntireBus(RCC_APB2);
	RCC_voidEnablePeripheralClock_EntireBus(RCC_APB1); /*  UART2 / UART3	*/
	/*	Systick	  F=Fcpu/8 =1Mhz and tick time=1us		*/
	STK_voidInit();
	/* 	GPIO 			*/
	DIO_Init();
	DIO_InitPin(PINA0, DIO_E_INPUT_ANALOG);        /* ADC Channel 0 / Potentiometer */
	DIO_InitPin(PINA1, DIO_E_INPUT_ANALOG);        /* ADC Channel 1 / ldr sensor    */
	DIO_InitPin(PINA2, DIO_E_OUTPUT_2MHZ_PUSH);    /* GPIO          / LCD RS        */
	DIO_InitPin(PINA3, DIO_E_OUTPUT_2MHZ_PUSH);    /* GPIO          / LCD EN        */
	DIO_InitPin(PINA4, DIO_E_OUTPUT_2MHZ_PUSH);    /* GPIO          / LCD D4        */
	DIO_InitPin(PINA5, DIO_E_OUTPUT_2MHZ_PUSH);    /* GPIO          / LCD D5        */
	DIO_InitPin(PINA6, DIO_E_OUTPUT_2MHZ_PUSH);    /* GPIO          / LCD D6        */
	DIO_InitPin(PINA7, DIO_E_OUTPUT_2MHZ_PUSH);    /* GPIO          / LCD D7        */
	DIO_InitPin(PINA8, DIO_E_OUTPUT_2MHZ_PUSH);    /* GPIO          / RELAY - DOOR LOCK */
	/* 	UART 1 PINs Init  */
	DIO_InitPin(PINA9, DIO_E_OUTPUT_2MHZ_AF_PP);    /* TX1 */
	DIO_InitPin(PINA10, DIO_E_INPUT_PULL_UP);       /* RX1 / AVR TX*/
	/* 	Timer 2 PINs Init */
	DIO_InitPin(PINB0, DIO_E_OUTPUT_2MHZ_AF_PP);    /* TIM3 CH3 / Fan Speed      */
	DIO_InitPin(PINB1, DIO_E_OUTPUT_2MHZ_AF_PP);    /* TIM3 CH4 / LEDs Adjustment */
	/* 	ADC Init                     		*/
	ADC_voidInit();
	/* 	LCD Init                     		*/
	LCD_Init();
	/*	UART init &	Enable	*/
	UART_voidInit(&uart1);
	/*	timer init & Enable	  */
	TimerInit(&timer3);
	/*  PWM init & Enable */
	timer_voidGPWM(&PWM3_CH3); /* TIM3 CH3 / Fan Speed      */
	timer_voidGPWM(&PWM3_CH4); /* TIM3 CH4 / LEDs Adjustment */
	/*variables*/
	u8 command=0,light_flag=LIGHT_MANUAL,fan_flag=FAN_MANUAL,lock_flag=LOCK_CLOSE,fan_last_manual=0,light_last_manual=0,ldr_Read=0,pot_Read=0;
	u32 ldr_update_counter=0,pot_update_counter=0;
	LCD_WriteStringXY(0, 0, SCREEN1L0);
	LCD_WriteStringXY(1, 0, SCREEN1L1);
	STK_voidSetBusyWait(Welcome_Screen_Delay);
	LCD_WriteStringXY(0, 0, SCREEN2L0);
	LCD_WriteStringXY(1, 0, SCREEN2L1);
	LCD_WriteCharXY(0, 14,lock_flag);
	LCD_WriteCharXY(1, 2,light_flag);
	if(LIGHT_MANUAL==light_flag){LCD_WriteNumberXY(1, 3,light_last_manual);}
	else if(LIGHT_AUTO==light_flag){LCD_WriteNumberXY(1, 3,ldr_Read);}
	LCD_WriteCharXY(1, 10,fan_flag);
	if(FAN_MANUAL==fan_flag){LCD_WriteNumberXY(1, 11,fan_last_manual);}
	else if(FAN_AUTO==fan_flag){LCD_WriteNumberXY(1, 11,pot_Read);}


	while(1)
	{
		switch(CurrentState)
		{
		case RECIVING_COMMANDS:
			/*There is a Recived Command */
			if(UART_u8ReciveCharPeriodic(&uart1,&command))   CurrentState = CHECKING_COMMANDS_VIDALITY ;
			else          		                             CurrentState = RECIVING_ADC_READINGS ;
			break;

		case CHECKING_COMMANDS_VIDALITY:
			if(OPEN_CLOSE_LOCK==command)          CurrentState = COMMAND1_VALID;
			else if(FAN_AUTO_MANUAL==command)     CurrentState = COMMAND2_VALID;
			else if(LIGHT_AUTO_MANUAL==command)   CurrentState = COMMAND3_VALID;

			else if((STOP_LIGHT     ==command)&&(LIGHT_MANUAL==light_flag))    CurrentState = COMMAND4_VALID;
			else if((START_LIGHT_100==command)&&(LIGHT_MANUAL==light_flag))    CurrentState = COMMAND5_VALID;
			else if((START_LIGHT_75 ==command)&&(LIGHT_MANUAL==light_flag))    CurrentState = COMMAND6_VALID;
			else if((START_LIGHT_50 ==command)&&(LIGHT_MANUAL==light_flag))    CurrentState = COMMAND7_VALID;
			else if((START_LIGHT_25 ==command)&&(LIGHT_MANUAL==light_flag))    CurrentState = COMMAND8_VALID;
			else if((START_LIGHT_10 ==command)&&(LIGHT_MANUAL==light_flag))    CurrentState = COMMAND14_VALID;

			else if((START_FAN_100  ==command)&&(FAN_MANUAL==fan_flag))        CurrentState = COMMAND9_VALID;
			else if((START_FAN_75   ==command)&&(FAN_MANUAL==fan_flag))        CurrentState = COMMAND10_VALID;
			else if((START_FAN_50   ==command)&&(FAN_MANUAL==fan_flag))        CurrentState = COMMAND11_VALID;
			else if((START_FAN_25   ==command)&&(FAN_MANUAL==fan_flag))        CurrentState = COMMAND12_VALID;
			else if((STOP_FAN       ==command)&&(FAN_MANUAL==fan_flag))        CurrentState = COMMAND13_VALID;
			else if((START_FAN_10   ==command)&&(FAN_MANUAL==fan_flag))        CurrentState = COMMAND15_VALID;



			else if((CurrentState!=COMMAND1_VALID    || CurrentState!=COMMAND2_VALID     || CurrentState!=COMMAND3_VALID
					|| CurrentState!=COMMAND4_VALID  || CurrentState!=COMMAND5_VALID || CurrentState!=COMMAND6_VALID
					|| CurrentState!=COMMAND7_VALID  || CurrentState!=COMMAND8_VALID || CurrentState!=COMMAND9_VALID
					|| CurrentState!=COMMAND10_VALID || CurrentState!=COMMAND11_VALID|| CurrentState!=COMMAND12_VALID
					|| CurrentState!=COMMAND13_VALID )&& CurrentState==CHECKING_COMMANDS_VIDALITY  )
				CurrentState=COMMANDS_UNVALID;
			command=0;

			break;

		case COMMAND1_VALID:
			/*OPEN or Close Lock*/
			if(LOCK_OPEN==lock_flag)
			{
				DIO_WritePin(PINA8,HIGH);                                                /* CLOSE relay          */
				lock_flag=LOCK_CLOSE;                                                    /* CHANGE LOCK Flag to CLOSE  */

				LCD_WriteStringXY(0, 0, SCREEN4L0);                                      /* DOOR Opened Screen   */
				LCD_WriteStringXY(1, 0, SCREEN4L1_2);                                    /* DOOR Opened Screen   */
				STK_voidSetBusyWait(Events_Screen_Delay);                                /* DOOR Opened Screen delay */
				LCD_WriteStringXY(0, 0, SCREEN2L0);                                      /* MAIN Screen   */
				LCD_WriteStringXY(1, 0, SCREEN2L1);                                      /* MAIN Screen   */
				LCD_WriteCharXY(0, 14,lock_flag);                                        /* Update Lock Flag   */
				LCD_WriteCharXY(1, 2,light_flag);                                        /* Update light Flag   */
				if(LIGHT_MANUAL==light_flag){LCD_WriteNumberXY(1, 3,light_last_manual);} /* Update LIGHT PERCENTAGE for MANUAL  */
				else if(LIGHT_AUTO==light_flag){LCD_WriteNumberXY(1, 3,ldr_Read);}       /* Update LIGHT PERCENTAGE for AUTO  */
				LCD_WriteCharXY(1, 10,fan_flag);                                         /* Update FAN Flag   */
				if(FAN_MANUAL==fan_flag){LCD_WriteNumberXY(1, 11,fan_last_manual);}      /* Update FAN PERCENTAGE for MANUAL  */
				else if(FAN_AUTO==fan_flag){LCD_WriteNumberXY(1, 11,pot_Read);}          /* Update FAN PERCENTAGE for AUTO  */
			}
			else if (LOCK_CLOSE==lock_flag)
			{
				DIO_WritePin(PINA8,LOW);                                                 /* OPEN relay          */
				lock_flag=LOCK_OPEN;                                                     /* CHANGE LOCK Flag to OPEN  */

				LCD_WriteStringXY(0, 0, SCREEN4L0);                                      /* DOOR Closed Screen   */
				LCD_WriteStringXY(1, 0, SCREEN4L1);                                      /* DOOR Closed Screen   */
				STK_voidSetBusyWait(Events_Screen_Delay);                                /* DOOR Closed Screen delay */
				LCD_WriteStringXY(0, 0, SCREEN2L0);                                      /* MAIN Screen   */
				LCD_WriteStringXY(1, 0, SCREEN2L1);                                      /* MAIN Screen   */
				LCD_WriteCharXY(0, 14,lock_flag);                                        /* Update Lock Flag   */
				LCD_WriteCharXY(1, 2,light_flag);                                        /* Update light Flag   */
				if(LIGHT_MANUAL==light_flag){LCD_WriteNumberXY(1, 3,light_last_manual);} /* Update LIGHT PERCENTAGE for MANUAL  */
				else if(LIGHT_AUTO==light_flag){LCD_WriteNumberXY(1, 3,ldr_Read);}       /* Update LIGHT PERCENTAGE for AUTO  */
				LCD_WriteCharXY(1, 10,fan_flag);                                         /* Update FAN Flag   */
				if(FAN_MANUAL==fan_flag){LCD_WriteNumberXY(1, 11,fan_last_manual);}      /* Update FAN PERCENTAGE for MANUAL  */
				else if(FAN_AUTO==fan_flag){LCD_WriteNumberXY(1, 11,pot_Read);}          /* Update FAN PERCENTAGE for AUTO  */


			}
			CurrentState=RECIVING_ADC_READINGS;
			break;
		case COMMAND2_VALID:
			/*Fan Auto or Manual*/
			if(FAN_AUTO==fan_flag)
			{
				//fan_last_manual  make pwm of tim3 ch4 at last manual value
				PWM3_CH3.duty=fan_last_manual;
				timer_voidGPWM(&PWM3_CH3);
				fan_flag=FAN_MANUAL;
				LCD_WriteStringXY(0, 0, SCREEN5L0);                                      /* FAN MANUAL Screen   */
				LCD_WriteStringXY(1, 0, SCREEN5L1);                                      /* FAN MANUAL Screen   */
				STK_voidSetBusyWait(Events_Screen_Delay);                                /* FAN MANUAL Screen delay */
				LCD_WriteStringXY(0, 0, SCREEN2L0);                                      /* MAIN Screen   */
				LCD_WriteStringXY(1, 0, SCREEN2L1);                                      /* MAIN Screen   */
				LCD_WriteCharXY(0, 14,lock_flag);                                        /* Update Lock Flag   */
				LCD_WriteCharXY(1, 2,light_flag);                                        /* Update light Flag   */
				if(LIGHT_MANUAL==light_flag){LCD_WriteNumberXY(1, 3,light_last_manual);} /* Update LIGHT PERCENTAGE for MANUAL  */
				else if(LIGHT_AUTO==light_flag){LCD_WriteNumberXY(1, 3,ldr_Read);}       /* Update LIGHT PERCENTAGE for AUTO  */
				LCD_WriteCharXY(1, 10,fan_flag);                                         /* Update FAN Flag   */
				LCD_WriteNumberXY(1, 11,fan_last_manual);                                /* Update FAN PERCENTAGE for MANUAL  */
			}
			else if (FAN_MANUAL==fan_flag)
			{
				//make pwm of tim3 ch3 at the adc READ Equivalent
				PWM3_CH3.duty=pot_Read;
				timer_voidGPWM(&PWM3_CH3);
				fan_flag=FAN_AUTO;
				LCD_WriteStringXY(0, 0, SCREEN5L0);                                      /* FAN AUTO Screen   */
				LCD_WriteStringXY(1, 0, SCREEN5L1_2);                                    /* FAN AUTO Screen   */
				STK_voidSetBusyWait(Events_Screen_Delay);                                /* FAN AUTO Screen delay */
				LCD_WriteStringXY(0, 0, SCREEN2L0);                                      /* MAIN Screen   */
				LCD_WriteStringXY(1, 0, SCREEN2L1);                                      /* MAIN Screen   */
				LCD_WriteCharXY(0, 14,lock_flag);                                        /* Update Lock Flag   */
				LCD_WriteCharXY(1, 2,light_flag);                                        /* Update light Flag   */
				if(LIGHT_MANUAL==light_flag){LCD_WriteNumberXY(1, 3,light_last_manual);} /* Update LIGHT PERCENTAGE for MANUAL  */
				else if(LIGHT_AUTO==light_flag){LCD_WriteNumberXY(1, 3,ldr_Read);}       /* Update LIGHT PERCENTAGE for AUTO  */
				LCD_WriteCharXY(1, 10,fan_flag);                                         /* Update FAN Flag   */
				LCD_WriteNumberXY(1, 11,pot_Read);                                       /* Update FAN PERCENTAGE for AUTO  */
			}
			CurrentState=RECIVING_ADC_READINGS;
			break;
		case COMMAND3_VALID:
			if(LIGHT_AUTO==light_flag)
			{
				//Light_last_manual  make pwm of tim3 ch4 at last manual value
				PWM3_CH4.duty=light_last_manual;
				timer_voidGPWM(&PWM3_CH4);
				light_flag=LIGHT_MANUAL;

				LCD_WriteStringXY(0, 0, SCREEN5L0_2);                                    /* LIGHTS MANUAL Screen   */
				LCD_WriteStringXY(1, 0, SCREEN5L1);                                      /* LIGHTS MANUAL Screen   */
				STK_voidSetBusyWait(Events_Screen_Delay);                                /* LIGHTS MANUAL Screen delay */
				LCD_WriteStringXY(0, 0, SCREEN2L0);                                      /* MAIN Screen   */
				LCD_WriteStringXY(1, 0, SCREEN2L1);                                      /* MAIN Screen   */
				LCD_WriteCharXY(0, 14,lock_flag);                                        /* Update Lock Flag   */
				LCD_WriteCharXY(1, 2,light_flag);                                        /* Update light Flag   */
				LCD_WriteNumberXY(1, 3,light_last_manual);                               /* Update LIGHT PERCENTAGE for MANUAL  */
				LCD_WriteCharXY(1, 10,fan_flag);                                         /* Update FAN Flag   */
				if(FAN_MANUAL==fan_flag){LCD_WriteNumberXY(1, 11,fan_last_manual);}      /* Update FAN PERCENTAGE for MANUAL  */
				if(FAN_AUTO==fan_flag){LCD_WriteNumberXY(1, 11,pot_Read);LCD_WriteCharXY(1,5,' ');}               /* Update FAN PERCENTAGE for AUTO  */
			}
			else if (LIGHT_MANUAL==light_flag)
			{
				//make pwm of tim3 ch4 at the adc READ Equivalent
				PWM3_CH4.duty=ldr_Read;
				timer_voidGPWM(&PWM3_CH4);
				light_flag=LIGHT_AUTO;

				LCD_WriteStringXY(0, 0, SCREEN5L0_2);                                    /* LIGHTS AUTO Screen   */
				LCD_WriteStringXY(1, 0, SCREEN5L1_2);                                    /* LIGHTS AUTO Screen   */
				STK_voidSetBusyWait(Events_Screen_Delay);                                /* LIGHTS AUTO Screen delay */
				LCD_WriteStringXY(0, 0, SCREEN2L0);                                      /* MAIN Screen   */
				LCD_WriteStringXY(1, 0, SCREEN2L1);                                      /* MAIN Screen   */
				LCD_WriteCharXY(0, 14,lock_flag);                                        /* Update Lock Flag   */
				LCD_WriteCharXY(1, 2,light_flag);                                        /* Update light Flag   */
				LCD_WriteNumberXY(1, 3,ldr_Read);                                        /* Update LIGHT PERCENTAGE for AUTO  */
				LCD_WriteCharXY(1, 10,fan_flag);                                         /* Update FAN Flag   */
				if(FAN_MANUAL==fan_flag){LCD_WriteNumberXY(1, 11,fan_last_manual);}      /* Update FAN PERCENTAGE for MANUAL  */
				if(FAN_AUTO==fan_flag){LCD_WriteNumberXY(1, 11,pot_Read);LCD_WriteCharXY(1,5,' ');}               /* Update FAN PERCENTAGE for AUTO  */

			}
			CurrentState=RECIVING_ADC_READINGS;
			break;
		case COMMAND4_VALID:
			/*stop Lights*/
			//make pwm of tim3 ch4 at 0
			PWM3_CH4.duty=0;
			timer_voidGPWM(&PWM3_CH4);
			light_last_manual=0;
			LCD_WriteNumberXY(1, 3,light_last_manual);                               /* Update LIGHT PERCENTAGE for MANUAL  */
			LCD_WriteStringXY(1,4,"  ");
			CurrentState=RECIVING_ADC_READINGS;
			break;
		case COMMAND5_VALID:
			/*START_LIGHT_100*/
			//make pwm of tim3 ch4 at 100
			PWM3_CH4.duty=100;
			timer_voidGPWM(&PWM3_CH4);
			light_last_manual=100;
			LCD_WriteNumberXY(1, 3,light_last_manual);                               /* Update LIGHT PERCENTAGE for MANUAL  */

			CurrentState=RECIVING_ADC_READINGS;
			break;
		case COMMAND6_VALID:
			/*START_LIGHT_75*/
			//make pwm of tim3 ch4 at 75
			PWM3_CH4.duty=75;
			timer_voidGPWM(&PWM3_CH4);
			light_last_manual=75;
			LCD_WriteNumberXY(1, 3,light_last_manual);                               /* Update LIGHT PERCENTAGE for MANUAL  */
			LCD_WriteCharXY(1,5,' ');
			CurrentState=RECIVING_ADC_READINGS;
			break;
		case COMMAND7_VALID:
			/*START_LIGHT_50*/
			//make pwm of tim3 ch4 at 50
			PWM3_CH4.duty=50;
			timer_voidGPWM(&PWM3_CH4);
			light_last_manual=50;
			LCD_WriteNumberXY(1, 3,light_last_manual);                               /* Update LIGHT PERCENTAGE for MANUAL  */
			LCD_WriteCharXY(1,5,' ');
			CurrentState=RECIVING_ADC_READINGS;
			break;
		case COMMAND8_VALID:
			/*START_LIGHT_25*/
			//make pwm of tim3 ch4 at 25
			PWM3_CH4.duty=25;
			timer_voidGPWM(&PWM3_CH4);
			light_last_manual=25;
			LCD_WriteNumberXY(1, 3,light_last_manual);                               /* Update LIGHT PERCENTAGE for MANUAL  */
			LCD_WriteCharXY(1,5,' ');
			CurrentState=RECIVING_ADC_READINGS;
			break;
		case COMMAND9_VALID:
			/*START_FAN_100*/
			PWM3_CH3.duty=100;
			timer_voidGPWM(&PWM3_CH3);
			fan_last_manual=100;
			LCD_WriteNumberXY(1, 11,fan_last_manual);                                /* Update FAN PERCENTAGE for MANUAL  */
			CurrentState=RECIVING_ADC_READINGS;
			break;
		case COMMAND10_VALID:
			/*START_FAN_75*/
			PWM3_CH3.duty=75;
			timer_voidGPWM(&PWM3_CH3);
			fan_last_manual=75;
			LCD_WriteNumberXY(1, 11,fan_last_manual);                                /* Update FAN PERCENTAGE for MANUAL  */
			LCD_WriteCharXY(1,13,' ');
			CurrentState=RECIVING_ADC_READINGS;
			break;
		case COMMAND11_VALID:
			/*START_FAN_50*/
			PWM3_CH3.duty=50;
			timer_voidGPWM(&PWM3_CH3);
			fan_last_manual=50;
			LCD_WriteNumberXY(1, 11,fan_last_manual);                                /* Update FAN PERCENTAGE for MANUAL  */
			LCD_WriteCharXY(1,13,' ');
			CurrentState=RECIVING_ADC_READINGS;
			break;
		case COMMAND12_VALID:
			/*START_FAN_25*/
			PWM3_CH3.duty=25;
			timer_voidGPWM(&PWM3_CH3);
			fan_last_manual=25;
			LCD_WriteNumberXY(1, 11,fan_last_manual);                                /* Update FAN PERCENTAGE for MANUAL  */
			LCD_WriteCharXY(1,13,' ');
			CurrentState=RECIVING_ADC_READINGS;
			break;
		case COMMAND13_VALID:
			/*STOP_FAN*/
			PWM3_CH3.duty=0;
			timer_voidGPWM(&PWM3_CH3);
			fan_last_manual=0;
			LCD_WriteNumberXY(1, 11,fan_last_manual);                                /* Update FAN PERCENTAGE for MANUAL  */
			LCD_WriteStringXY(1,12,"  ");
			CurrentState=RECIVING_ADC_READINGS;
			break;
		case COMMAND14_VALID:
			/*START_LIGHT_10*/
			//make pwm of tim3 ch4 at 10
			PWM3_CH4.duty=10;
			timer_voidGPWM(&PWM3_CH4);
			light_last_manual=10;
			LCD_WriteNumberXY(1, 3,light_last_manual);                               /* Update LIGHT PERCENTAGE for MANUAL  */
			LCD_WriteCharXY(1,5,' ');
			CurrentState=RECIVING_ADC_READINGS;
			break;
		case COMMAND15_VALID:
			/*START_FAN_10*/
			PWM3_CH3.duty=10;
			timer_voidGPWM(&PWM3_CH3);
			fan_last_manual=10;
			LCD_WriteNumberXY(1, 11,fan_last_manual);                                /* Update FAN PERCENTAGE for MANUAL  */
			LCD_WriteCharXY(1,13,' ');
			CurrentState=RECIVING_ADC_READINGS;
			break;

		case COMMANDS_UNVALID:
			/*no command happens*/
			LCD_WriteStringXY(0, 0, SCREEN3L0);                                      /* INVALID COMMAND Screen   */
			LCD_WriteStringXY(1, 0, SCREEN3L1);                                      /* INVALID COMMAND Screen   */
			STK_voidSetBusyWait(Events_Screen_Delay);                                /* INVALID COMMAND Screen delay */
			LCD_WriteStringXY(0, 0, SCREEN2L0);                                      /* MAIN Screen   */
			LCD_WriteStringXY(1, 0, SCREEN2L1);                                      /* MAIN Screen   */
			LCD_WriteCharXY(0, 14,lock_flag);                                        /* Update Lock Flag   */
			LCD_WriteCharXY(1, 2,light_flag);                                        /* Update light Flag   */
			if(LIGHT_MANUAL==light_flag){LCD_WriteNumberXY(1, 3,light_last_manual);} /* Update LIGHT PERCENTAGE for MANUAL  */
			else if(LIGHT_AUTO==light_flag){LCD_WriteNumberXY(1, 3,ldr_Read);}       /* Update LIGHT PERCENTAGE for AUTO  */
			LCD_WriteCharXY(1, 10,fan_flag);                                         /* Update FAN Flag   */
			if(FAN_MANUAL==fan_flag){LCD_WriteNumberXY(1, 11,fan_last_manual);}      /* Update FAN PERCENTAGE for MANUAL  */
			if(FAN_AUTO==fan_flag){LCD_WriteNumberXY(1, 11,pot_Read);}               /* Update FAN PERCENTAGE for AUTO  */
			CurrentState=RECIVING_ADC_READINGS;
			break;
		case RECIVING_ADC_READINGS:
			/* ADC api for LDR */
			/* if different readings appear change Light , CurrentState = ADJUSTING_LIGHT  */


			if(pot_update_counter==0)
			{
				pot_Read=POT_PercentRead(0);
				if(FAN_AUTO==fan_flag)
				{
					PWM3_CH3.duty=pot_Read;
					timer_voidGPWM(&PWM3_CH3);
					LCD_WriteStringXY(1,12,"  ");
					LCD_WriteNumberXY(1,11,pot_Read);          /* Update FAN PERCENTAGE for AUTO  */
				}
				pot_update_counter++;
			}
			else if(pot_update_counter<POT_UPDATE_COUNT) {pot_update_counter++;}
			else if(pot_update_counter==POT_UPDATE_COUNT) {pot_update_counter=0;}
			if(ldr_update_counter==0)
			{
				ldr_Read=100-LDR_PercentRead(1);
				if(LIGHT_AUTO==light_flag)
				{
					if(ldr_Read>50)
					{
					PWM3_CH4.duty=(ldr_Read);
					timer_voidGPWM(&PWM3_CH4);
					LCD_WriteStringXY(1,4,"  ");
					LCD_WriteNumberXY(1,3,ldr_Read);
					}
					else if(ldr_Read<=50)
					{
					PWM3_CH4.duty=(ldr_Read);
					timer_voidGPWM(&PWM3_CH4);
					LCD_WriteStringXY(1,4,"  ");
					LCD_WriteNumberXY(1,3,ldr_Read);
					}                                /* Update LIGHT PERCENTAGE for AUTO  */
				}
				ldr_update_counter++;
			}
			else if(ldr_update_counter<LDR_UPDATE_COUNT) {ldr_update_counter++;}
			else if(ldr_update_counter==LDR_UPDATE_COUNT) {ldr_update_counter=0;}


			     CurrentState = RECIVING_COMMANDS;       break;
		default: CurrentState = RECIVING_ADC_READINGS ;  break;
		}
	}
}